<?php

namespace App\Controller;
use Cake\Http\Exception\NotFoundException;

class FavouritesController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->Auth->allow(['add']);
    }

    public function index(){
        $f = $this->Favourites->find();
        $this->set(compact('f'));
    }

    public function add($artist_id, $user_id){
        //Crée une entité vide
        $new = $this->Favourites->newEntity();
        $new->artist_id = $artist_id;
        $new->user_id = $user_id;

        $f = $this->Favourites->find();
        $existantFavourite = $f->where(['artist_id' => $artist_id, 'user_id' => $user_id])->count();

        if($existantFavourite === 0){
            if($this->Favourites->save($new)){
                $this->Flash->success('Ok');
                return $this->redirect(['controller' => 'Artists', 'action' => 'view', $artist_id]);
            }
            $this->Flash->error('Planté');
        }

        //Envoie la variable dans la vue
        $this->redirect(['controller' => 'Artists', 'action' => 'view', $artist_id, ]);
    }

    public function delete($artist_id, $user_id){
        if($this->request->is(['post', 'delete'])){
            //on récupère l'élément ciblé
            $f = $this->Favourites->find();
            $delF = $f->where(['artist_id' => $artist_id, 'user_id' => $user_id])->first();

            if($this->Favourites->delete($delF)){
                $this->Flash->success('L\'artiste n\'est plus dans vos favoris');
                return $this->redirect(['controller' => 'artists', 'action' => 'view', $artist_id]);
            } else {
                $this->Flash->error('Suppresion du favoris ratée');
                return $this->redirect(['controller' => 'artists', 'action' => 'view', $artist_id]);
            }
        } else {
            throw new NotFoundException('Tu te crois malin ? C\'est pas comme ça que ça marche !');
        }
    }

}